### PR TITLE
Add HasDocs instance

### LINKED ISSUE #10: provide HasDocs instance for MultipartForm
I'd like to send a PR adding a `HasDocs` instance for `MultipartForm`.

I have an instance `HasDocs` for `MultipartForm` working in my current project.  Here's the full [code](https://github.com/kitty-cat-map/kitty-cat-map-backend/blob/0d206c8a931ab1f0842b137d06e9247b8689cffd/kitty-cat-map-doc/src/Kitty/Doc.hs#L28-L105).

Below I will explain the different parts.

Here is the `HasDocs` instance for `MultipartForm`:

```haskell
instance (HasDocs api, ToMultipartSample a) => HasDocs (MultipartForm a :> api) where
  docsFor
    :: Proxy (MultipartForm a :> api)
    -> (Endpoint, Action)
    -> DocOptions
    -> API
  docsFor _ (endpoint, action) opts =
    let newAction =
          action
            & notes <>~
                [ toMultipartNotes
                    (view maxSamples opts)
                    (Proxy :: Proxy a)
                ]
    in docsFor (Proxy :: Proxy api) (endpoint, newAction) opts
```

You can see that it is using the `ToMultipartSample` class.  This is similar to the `ToSample` class that currently exists in servant-docs:

```haskell
class ToMultipartSample a where
  toMultipartSamples :: Proxy a -> [(Text, MultipartData)]
```

Here's a datatype I'm using in my app and the instance of `ToMultipartSample` for it:

```haskell
data PostImgForm = PostImgForm
  { filename :: FilePath
  , date :: UTCTime
  , geom :: Geom
  }

instance ToMultipartSample PostImgForm where
  toMultipartSamples :: Proxy PostImgForm -> [(Text, MultipartData)]
  toMultipartSamples Proxy =
    [ ( "normal image upload"
      , MultipartData
          [ Input "date" "2017-09-10 08:23 Z"
          , Input "lat" "-33"
          , Input "lon" "-100"
          ]
          [ FileData
              "file"
              "temp-cat-image.jpg"
              "image/jpeg"
              "/tmp/tmppath.file"
          ]
      )
    , ( "upload sample 2"
      , MultipartData
          [ Input "date" "2017-08-22 13:23 Z"
          , Input "lat" "50"
          , Input "lon" "150"
          ]
          [ FileData
              "file"
              ""
              "image/jpeg"
              ""
          ]
      )
    ]
```

There are some additional helper functions used in the `HasDocs` instance for `MultipartForm`.  They can be found in the code linked above.

Running this for a route in my application produces documentation that looks like this:

```markdown
## POST /v0/image

#### Multipart Request Samples

This endpoint takes `multipart/form-data` requests.  The following is a list of sample requests:

- normal image upload
    - textual inputs (any `<input>` type but file):
        - *date*: `2017-09-10 08:23 Z`
        - *lat*: `-33`
        - *lon*: `-100`
    - file inputs (any HTML input that looks like `<input type="file" name="somefile" />`):
        - *file*, content-type: `image/jpeg`

- upload sample 2
    - textual inputs (any `<input>` type but file):
        - *date*: `2017-08-22 13:23 Z`
        - *lat*: `50`
        - *lon*: `150`
    - file inputs (any HTML input that looks like `<input type="file" name="somefile" />`):
        - *file*, content-type: `image/jpeg`

#### Authentication

Clients must supply the following data

#### Response:

- Status code 200
- Headers: []

- Supported content types are:

    - `application/json;charset=utf-8`
    - `application/json`

- sample uuid key

``javascript
{"data":"0359141a-9ce8-4ca9-b93c-d9d017ece471"}
``

...
```

---------------------------------------------------------------------------------------------------

If I send a PR, I'm wondering whether I should just throw this `HasDocs` instance in with the current code, or whether I should split this package into servant-multipart and servant-multipart-docs (similar to how servant itself is split up)?

I could also go ahead and split this package up into `servant-multipart`, `servant-multipart-docs`, and `servant-multipart-server`.  This would make it easier for someone to come along and implement `servant-multipart-client`.

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR adds a `HasDocs` instance for `MultipartForm`.

It also adds a `ToMultipartSample` class so that users can easily add documentation for their types.  This is similar to the [`ToSample`](https://hackage.haskell.org/package/servant-docs-0.11/docs/Servant-Docs.html#t:ToSample) class from [servant-docs](https://hackage.haskell.org/package/servant-docs-0.11).

The output markdown created by the `HasDocs` instance can be seen [here](https://github.com/haskell-servant/servant-multipart/issues/10#issue-263186235).

This PR also adds a `stack.yaml` to make development easier for people using stack.  However, if you don't want a `stack.yaml` in this repository, let me know and a I'll remove it!

Closes #10.

### CODE REVIEW

**Comment by alpmestan** [comment]
I don't mind having `stack.yaml` files around for those who prefer `stack` don't worry. The PR looks good to me! @phadej objections?

**Comment by cdepillabout** [comment]
@phadej Any thoughts about this `HasDocs` instance?

**Comment by alpmestan** [comment]
9 days is enough to chime in. Merging this. We can still tweak those docs instance later if there's a problem.

**Comment by cdepillabout** [comment]
@alpmestan Thanks!

**Pull request merged**
