### PR TITLE
Test/allow GHC 9.6, 9.8

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by ysangkok** [comment]
@maksbotan please review if you get some time

**Comment by ysangkok** [comment]
This addresses:

* https://github.com/commercialhaskell/stackage/issues/7216
* https://github.com/commercialhaskell/stackage/issues/7222

**Comment by maksbotan** [comment]
Hi @ysangkok! Looks good, I've made Hackage revisions.

Please ping me or request review explicitly, because these PRs get lost in a ton of emails, sadly.

Is there a PR for main servant repo as well?

**Comment by ysangkok** [comment]
I've already updated the main Servant repo, it was here: https://github.com/haskell-servant/servant/pull/1714. Revisions were already made.

**Pull request merged**
